### ISSUE TITLE
Location of config file

### ISSUE THREAD

**Issue by theduke** [Drakulix/fireplace#30]
The XDG / freedesktop guidelines say that the config file should live in a subdirectory of XDG_CONFIG_DIR.

I can dig it out if you want to.

I personally like this. It allows easier expansion and gives a clean structure.

So the default paths checked would be `$XDG_CONFIG_DIR/fireplace/fireplace.yml` or `~/.config/fireplace/fireplace.yml`.

What do you think?

**Comment by Timidger** [comment]
This is the way Way Cooler does it, and I find that applications that use that folder by default easier to use. I don't have to go rooting around for a configuration file, it's always in the same directory

**Comment by Drakulix** [comment]
I find all those folders quite annoying, because usually most applications only need one configuration file anyways, but I would be totally fine with searching for that path as well and even using it over the current path.

I just would like to keep the current option, because although it is nice, that there guidelines, and we should totally respect and follow them, this is also a matter of personal preference.

**Comment by theduke** [comment]
To keep checking ~/.config/fireplace.yml is perfectly fine of course, and is actually pretty much unavoidable since you passed `1.0` already. ;)

**Comment by Drakulix** [comment]
> To keep checking ~/.config/fireplace.yml is perfectly fine of course, and is actually pretty much unavoidable since you passed 1.0 already. ;)

Well the location is considered public api and I am following semver, so I could just increase the major version of course, which I am willing to do, if it provides any benefit (the reason I am already at 3.0 since today). But it is of course bad practice to do that this regularly and completely unnecessary in this case.

I have finally reached a stable config format today, so I really don't want to bump the major version at least for the binary in the near future anymore. ^^

**Comment by Drakulix** [comment]
Done. Please test and provide feedback once 3.0.2 is tagged and out. (Sometime today)
